### ISSUE TITLE
pip3 install psycopg2

### ISSUE THREAD

**Issue by ardipta** [farhanswe/odoo-install#1]
**Debian/Ubuntu**
Python 3

> sudo apt install libpq-dev python3-dev

You might need to install python3.8-dev or similar for e.g. Python 3.8.
Python 21

> sudo apt install libpq-dev python-dev

If that's not enough, try

> sudo apt install build-essential
 or
> sudo apt install postgresql-server-dev-all

as well before installing psycopg2 again.

**Comment by farhanswe** [comment]
issue solve and update
